name: Build & Deploy to AKS (main)

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: laendletechregistry.azurecr.io
  IMAGE_REPO: careconnectapp

jobs:
# ------------ BUILD & PUSH ------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login -n ${{ env.REGISTRY }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:latest

# ------------ DEPLOY TO AKS ------------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name:  ${{ secrets.AKS_NAME }}

      - name: Replace image tag in deployment
        run: |
          sed -i 's|PLACEHOLDER|${{ github.sha }}|' k8s/deployment.yaml
  
      - uses: azure/k8s-deploy@v4
        with:
          namespace: careconnect
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/ingress.yaml
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ github.sha }}
