name: Build & Deploy to AKS (main)

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: laendletechregistry.azurecr.io
  IMAGE_REPO: ${{ github.repository }}

jobs:
# ------------ BUILD & PUSH ------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1                            # Azure-Login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login -n ${{ env.REGISTRY }}        # ACR-Login

      - uses: docker/setup-buildx-action@v3             # BuildKit

      - uses: docker/build-push-action@v6               # Image bauen & pushen
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:latest

# ------------ DEPLOY TO AKS ------------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name:  ${{ secrets.AKS_NAME }}

      - name: Show tree (Debug)
        run: ls -R 
  
      # Bild-Tag im Manifest ersetzen
      - name: Stamp image tag
        run: |
          sed -i 's|PLACEHOLDER|${{ github.sha }}|' k8s/deployment.yaml
  
      # Anwenden / Rollout
      - uses: azure/k8s-deploy@v4
        with:
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/ingress.yaml
          images: |
            laendletechregistry.azurecr.io/nre7459/careconnectapp:${{ github.sha }}

